select
    trim("Employee_Name")                               as employee_name,
    "EmpID"                                             as emp_id,
    ("MarriedID" = 1)                                   as is_married,
    "MaritalStatusID"                                   as marital_status_id,
    "GenderID"                                          as gender_id,
    "EmpStatusID"                                       as emp_status_id,
    "DeptID"                                            as dept_id,
    "PerfScoreID"                                       as perf_score_id,
    "FromDiversityJobFairID"                            as from_diversity_job_fair_id,
    "Salary"                                            as salary,
    ("Termd" = 1)                                       as is_terminated,
    "PositionID"                                        as position_id,
    trim("Position")                                    as position,
    trim("State")                                       as state,
    lpad("Zip"::text, 5, '0')                           as zip,
    to_date(
        split_part("DOB", '/', 1) || '/' || split_part("DOB", '/', 2) || '/19' || split_part("DOB", '/', 3),
        'MM/DD/YYYY'
    )                                                    as date_of_birth,
    trim("Sex")                                         as sex,
    trim("MaritalDesc")                                 as marital_desc,
    trim("CitizenDesc")                                 as citizen_desc,
    trim("HispanicLatino")                              as hispanic_latino,
    trim("RaceDesc")                                    as race_desc,
    to_date("DateofHire", 'MM/DD/YYYY')                 as date_of_hire,
    to_date("DateofTermination", 'MM/DD/YYYY')          as date_of_termination,
    trim("TermReason")                                  as term_reason,
    trim("EmploymentStatus")                            as employment_status,
    trim("Department")                                  as department,
    trim("ManagerName")                                 as manager_name,
    "ManagerID"                                         as manager_id,
    trim("RecruitmentSource")                           as recruitment_source,
    trim("PerformanceScore")                            as performance_score,
    "EngagementSurvey"                                  as engagement_survey,
    "EmpSatisfaction"                                   as emp_satisfaction,
    "SpecialProjectsCount"                              as special_projects_count,
    to_date("LastPerformanceReview_Date", 'MM/DD/YYYY') as last_performance_review_date,
    "DaysLateLast30"                                    as days_late_last_30,
    "Absences"                                          as absences
from {{ source('raw', 'hr_employees') }}
