x-airflow-common:
  &airflow-common
  build:
    context: ../..
    dockerfile: src/docker/Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    DBT_PROFILES_DIR: /opt/airflow/src/dbt/hr_dwh
  volumes:
    - ../dags:/opt/airflow/dags
    - ../ingestion:/opt/airflow/src/ingestion
    - ../dbt:/opt/airflow/src/dbt
    - ../../dataset:/opt/airflow/dataset
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: hr_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: hr_airflow_init
    entrypoint: /bin/bash
    command: -c "airflow db migrate && (airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true)"

  airflow-webserver:
    <<: *airflow-common
    container_name: hr_airflow_webserver
    restart: unless-stopped
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: hr_airflow_scheduler
    restart: unless-stopped
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  pgdata:
