name: 'hr_dwh'
version: '1.0.0'
config-version: 2

profile: 'hr_dwh'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hr_dwh:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
